### ISSUE TITLE
Doubly Linked List on Go

### ISSUE THREAD

**Issue by afrizal423** [afrizal423/where-we-Go#1]
Hello everyone, here someone wants to contribute to making a Doubly Linked List using the Go programming language.
The program is simple.
Please read it [here](https://github.com/afrizal423/where-we-Go/tree/master/data_structures/linked_list/doubly-linked-list)

If willing to contribute to this project.
Please comment below.
Then Fork this Repository
Pull back over here.

**Comment by pointerish** [comment]
Hey, I would like to help. Could you please assign this to me?

**Comment by afrizal423** [comment]
Hello @pointerish ,
OK ,,
I hope you understand the link I gave above.
