### ISSUE TITLE
Circular Linked List on Go

### ISSUE THREAD

**Issue by afrizal423** [afrizal423/where-we-Go#2]
Hello everyone, here someone wants to contribute to making a Circular Linked List using the Go programming language.
The program is simple.
Please read it [here](https://github.com/afrizal423/where-we-Go/tree/master/data_structures/linked_list/circular-linked-list)

If willing to contribute to this project.
Please comment below.
Then Fork this Repository
Pull back over here.

**Comment by stuckinforloop** [comment]
Can I work on this issue?

**Comment by afrizal423** [comment]
Hello @neel229 ,
OK ,,
I hope you understand the link I gave above.

**Comment by Shr03mink** [comment]
Please review my PR #15  for this issue @afrizal423
