### ISSUE TITLE
Queue on Go

### ISSUE THREAD

**Issue by afrizal423** [afrizal423/where-we-Go#3]
Hello everyone, here someone wants to contribute to making a Queue using the Go programming language.
The program is simple.
Please read it [here](https://github.com/afrizal423/where-we-Go/tree/master/data_structures/queue)

If willing to contribute to this project.
Please comment below.
Then Fork this Repository
Pull back over here.

**Comment by felipehfs** [comment]
Hello.Nice to meet you. I want to contribute.

**Comment by afrizal423** [comment]
Hello,
Thank you for your contribution to this project.
I respect and thank you very much
