### ISSUE TITLE
Stack on Go

### ISSUE THREAD

**Issue by afrizal423** [afrizal423/where-we-Go#4]
Hello everyone, here someone wants to contribute to making a Stack using the Go programming language.
The program is simple.
Please read it [here](https://github.com/afrizal423/where-we-Go/tree/master/data_structures/stack)

If willing to contribute to this project.
Please comment below.
Then Fork this Repository
Pull back over here.

**Comment by sjchoure** [comment]
I am here from Hacktober label search. 
I really appreciate your efforts. I can help you by contributing Stack Date Structure using GoLang.

**Comment by afrizal423** [comment]
Hello @saviourcode 
OK ,,
I hope you understand the link I gave above.

**Comment by sjchoure** [comment]
Hello, @afrizal423 ! Hope you doing well.
> I hope you understand the link I gave above.

Yes I do.
