### ISSUE TITLE
Selection Sort on Go

### ISSUE THREAD

**Issue by afrizal423** [afrizal423/where-we-Go#5]
Hello everyone, here someone wants to contribute to making a Selection Sort using the Go programming language.
The program is simple.
Please read it [here](https://github.com/afrizal423/where-we-Go/tree/master/algorithms/selection_sort)

If willing to contribute to this project.
Please comment below.
Then Fork this Repository
Pull back over here.

**Comment by Shr03mink** [comment]
would like to work on this

**Comment by afrizal423** [comment]
Hello @Shr03mink 
OK ,,
I hope you understand the link I gave above.

**Comment by Shr03mink** [comment]
yes.

**Comment by Shr03mink** [comment]
Please review my PR #12 @afrizal423
