### ISSUE TITLE
Insertion Sort on Go

### ISSUE THREAD

**Issue by afrizal423** [afrizal423/where-we-Go#6]
Hello everyone, here someone wants to contribute to making a Insertion Sort using the Go programming language.
The program is simple.
Please read it [here](https://github.com/afrizal423/where-we-Go/tree/master/algorithms/insertion_sort)

If willing to contribute to this project.
Please comment below.
Then Fork this Repository
Pull back over here.

**Comment by ssinghaldev** [comment]
Hey @afrizal423!

I would like to take this up!

**Comment by afrizal423** [comment]
Hello @ssinghaldev ,
OK ,,
I hope you understand the link I gave above.

**Comment by afrizal423** [comment]
another reference [Shell Short](https://github.com/afrizal423/where-we-Go/blob/master/algorithms/shell_short/shell_sort.go)

**Comment by ssinghaldev** [comment]
I understand at a higher level what you are trying to do. Also the references given are super useful.
I will write the code accordingly & send the PR

**Comment by ssinghaldev** [comment]
Hey sorry! I will be sending a PR by this weekend!
