### ISSUE TITLE
Shell Sort on Go

### ISSUE THREAD

**Issue by afrizal423** [afrizal423/where-we-Go#7]
Hello everyone, here someone wants to contribute to making a Shell Sort using the Go programming language.
The program is simple.
Please read it [here](https://github.com/afrizal423/where-we-Go/tree/master/algorithms/shell_short)

If willing to contribute to this project.
Please comment below.
Then Fork this Repository
Pull back over here.

**Comment by akwanmaroso** [comment]
hello, I am very interested to resolving this issue. can I solve the issue now?

**Comment by afrizal423** [comment]
Hello @akwanmaroso ,
OK ,
I hope you understand the link I gave above
